cd ~ && sudo perl -pi -e 'if(/jhbsscripts/){undef $_}' /etc/hosts
archivo='/etc/hosts'
hosts=$(cat $archivo)
lista='
0 www2.nevova.club #jhbsscripts
0 www1.palhet.pw #jhbsscripts
0 palhet.pw #jhbsscripts
0 www1.gasger.space #jhbsscripts
0 bughokk.win #jhbsscripts
0 adexchangeguru.com #jhbsscripts
0 crrepo.com #jhbsscripts
0 147630.monetizer.site  #jhbsscripts
0 192.168.cdn11.contentabc.com #jhbsscripts
0 247gamerz.com #jhbsscripts
0 activate.adobe.com #jhbsscripts
0 activate.tapatalk.com #jhbsscripts
0 active.cache.el-mundo.net #jhbsscripts
0 ad-ace.doubleclick.net #jhbsscripts
0 ad.amgdgt.com #jhbsscripts
0 ad.doubleclick.net #jhbsscripts
0 ads.ad4game.com #jhbsscripts
0 ads.mcanime.net #jhbsscripts
0 ads.redluckia.com #jhbsscripts
0 ads.youtube.com #jhbsscripts
0 aimfar.solution.weborama.fr #jhbsscripts
0 alert.mac-notification.com #jhbsscripts
0 alpha.mlot.xyz #jhbsscripts
0 anapixel.marca.com #jhbsscripts
0 b.scorecardresearch.com #jhbsscripts
0 bs.serving-sys.com #jhbsscripts
0 cache.elmundo.es #jhbsscripts
0 cartel.cubadebate.cu #jhbsscripts
0 cdn.amgdgt.com #jhbsscripts
0 cdn.hauleddes.com #jhbsscripts
0 chachagong24.com #jhbsscripts
0 click.alibaba.com #jhbsscripts
0 con.freefaxed.com #jhbsscripts
0 connect.facebook.net #jhbsscripts
0 cstatic.weborama.fr #jhbsscripts
0 doubleclick.net #jhbsscripts
0 doublepimp.com #jhbsscripts
0 download.com #jhbsscripts
0 download.mac-install.com #jhbsscripts
0 download.mackeeper.com #jhbsscripts
0 dstrack2.com #jhbsscripts
0 duoup.info #jhbsscripts
0 engine.adzerk.net #jhbsscripts
0 engine.phn.doublepimp.com #jhbsscripts
0 es.ign.com #jhbsscripts
0 estaticos.cookies.unidadeditorial.es #jhbsscripts
0 estaticos.latiendademarca.com #jhbsscripts
0 files.adform.net #jhbsscripts
0 googleadapis.l.google.com #jhbsscripts
0 googleads.g.doubleclick.net #jhbsscripts
0 googleadservices.com #jhbsscripts
0 gtms03.alicdn.com #jhbsscripts
0 images.eplayer.performgroup.com #jhbsscripts
0 impes.tradedoubler.com #jhbsscripts
0 js.revsci.net #jhbsscripts
0 k.uecdn.es #jhbsscripts
0 lbs.plasticscarecrow.win #jhbsscripts
0 mac-security.amazingnewapps.com #jhbsscripts
0 mac-security.onlygoodapps.com #jhbsscripts
0 mac.system-alert1.com #jhbsscripts
0 mackeeper.com--index.info #jhbsscripts
0 mackeeper.com-ltd.net #jhbsscripts
0 mackeeper.install-la.es #jhbsscripts
0 mackeeper.install-latest.online #jhbsscripts
0 mackeeper.officialmacprotector.com #jhbsscripts
0 mackeeperapp.mackeeper.com #jhbsscripts
0 mackeeperapp2.mackeeper.com #jhbsscripts
0 mackeeperapp3.mackeeper.com #jhbsscripts
0 macpurifier.com #jhbsscripts
0 media.fastclick.net #jhbsscripts
0 media.trafficjunky.net #jhbsscripts
0 monetizer.site #jhbsscripts
0 newsoft12.livecheckultimateformacandpc.club #jhbsscripts
0 ocdn01.safe-install.net #jhbsscripts
0 offer.alibaba.com #jhbsscripts
0 onclickads.net #jhbsscripts
0 openx.fichajes.net #jhbsscripts
0 p42n.com #jhbsscripts
0 pagead.l.doubleclick.net #jhbsscripts
0 pagead2.googlesyndication.com #jhbsscripts
0 pl.atds.me #jhbsscripts
0 platform.twitter.com #jhbsscripts
0 pubads.g.doubleclick.net #jhbsscripts
0 reelzhot.com #jhbsscripts
0 rnulkg.com #jhbsscripts
0 rye.sptiappetters.club #jhbsscripts
0 s0.2mdn.net #jhbsscripts
0 s1.2mdn.net #jhbsscripts
0 safenetdir.com #jhbsscripts
0 safestdownloadsrus118.com #jhbsscripts
0 scdn.cxense.com #jhbsscripts
0 scorecardresearch.com #jhbsscripts
0 secure-ds.serving-sys.com #jhbsscripts
0 secure4pads.com #jhbsscripts
0 security-verified.info #jhbsscripts
0 security.com-verified.info #jhbsscripts
0 serve.popads.net #jhbsscripts
0 serve.williamhill.es #jhbsscripts
0 slowmacfaster.trade #jhbsscripts
0 software147updates.xyz #jhbsscripts
0 software153updates.xyz #jhbsscripts
0 software229updates.xyz #jhbsscripts
0 spanish.alibaba.com #jhbsscripts
0 sq2zz.allaff.jagg.info jagg.info #jhbsscripts
0 ssl.google-analytics.com #jhbsscripts
0 static.batanga.net #jhbsscripts
0 static.doubleclick.net #jhbsscripts
0 static.eplayer.performgroup.com #jhbsscripts
0 stats.g.doubleclick.net #jhbsscripts
0 stockgifttowers.com #jhbsscripts
0 survey.heeb.info #jhbsscripts
0 sw191update.xyz #jhbsscripts
0 terraclicks.com #jhbsscripts
0 tpc.googlesyndication.com #jhbsscripts
0 track.ctclinks.com #jhbsscripts
0 vht.tradedoubler.com #jhbsscripts
0 view.binlayer.com #jhbsscripts
0 weborama.com #jhbsscripts
0 wtp101.com #jhbsscripts
0 www-google-analytics.l.google.com #jhbsscripts
0 www-googletagmanager.l.google.com #jhbsscripts
0 xml.adventurefeeds.com #jhbsscripts
0 y31uv4ra1.vo.llnwd.net #jhbsscripts
0 yvizz.exclusiverewards.isos.info #jhbsscripts
0 zoxzz.exclusiverewards.huuj.info #jhbsscripts'
union=$(echo "$hosts" "$lista")
echo "$union" > hosts
sudo cp hosts /etc/hosts && rm -rf hosts
sudo killall -HUP mDNSResponder
clear && echo "BloqueaSitios.sh ha finalizado con exito,  se recomienda borrar la caché del navegador."
echo
#Para borrar el listado de sitios no permitidos por el fichero hosts ejecute en Terminal.app: sudo perl -pi -e 'if(/jhbsscripts/){undef $_}' /etc/hosts
